import {mkdirSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
const remote=()=>!!(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY);
function db(){
 if(process.env.VERCEL&&!remote())throw Error('Chưa cấu hình database. Quản trò cần hoàn thành bước Supabase trong README.');
 if(!globalThis.__gameDB){mkdirSync('.data',{recursive:true});const d=new DatabaseSync(process.env.GAME_DB_PATH||'.data/game.sqlite');d.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS game_rooms (code TEXT PRIMARY KEY, version INTEGER NOT NULL, state TEXT NOT NULL)');globalThis.__gameDB=d;}return globalThis.__gameDB;
}
async function request(path,options={}){const response=await fetch(process.env.SUPABASE_URL+'/rest/v1/'+path,{...options,headers:{apikey:process.env.SUPABASE_SERVICE_ROLE_KEY,Authorization:'Bearer '+process.env.SUPABASE_SERVICE_ROLE_KEY,'Content-Type':'application/json',...options.headers},cache:'no-store',signal:AbortSignal.timeout(12000)});if(!response.ok){console.error('Database HTTP',response.status);throw Error('Không kết nối được database. Kiểm tra cấu hình hoặc thử lại.');}return response.status===204?null:response.json();}
export async function get(code){if(remote()){const rows=await request('game_rooms?code=eq.'+code+'&select=version,state');return rows[0]||null;}const row=db().prepare('SELECT version,state FROM game_rooms WHERE code=?').get(code);return row?{version:row.version,state:JSON.parse(row.state)}:null;}
export async function insert(r){if(remote()){return request('rpc/game_insert',{method:'POST',body:JSON.stringify({p_code:r.code,p_state:r})});}try{db().prepare('INSERT INTO game_rooms VALUES (?,0,?)').run(r.code,JSON.stringify(r));return true;}catch(e){if(e.message.includes('UNIQUE'))return false;throw e;}}
export async function cas(code,version,state){if(remote())return request('rpc/game_cas',{method:'POST',body:JSON.stringify({p_code:code,p_version:version,p_state:state})});return db().prepare('UPDATE game_rooms SET state=?,version=version+1 WHERE code=? AND version=?').run(JSON.stringify(state),code,version).changes===1;}
export async function mutate(code,fn){for(let i=0;i<80;i++){const row=await get(code);if(!row)throw Error('Không tìm thấy phòng. Kiểm tra mã 6 ký tự.');const changed=fn(row.state);if(!changed)return row.state;if(await cas(code,row.version,row.state))return row.state;await new Promise(r=>setTimeout(r,5+Math.random()*25));}throw Error('Phòng đang bận, vui lòng thử lại.');}
